# -*- coding: utf-8 -*-
"""Sales_analysis_practice_project.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwvn_bOiRt7RSCSA8wnYXCIfZmjn4557
"""

# Sales Performance Analysis
#
# A simple statistical analysis of weekly sales data to understand:
# - Central tendency
# - Variability
# - Business insights

# -------------------------------
# Data Section
# -------------------------------
# Sample weekly sales data (in units)
sales = [500, 700, 600, 800, 900, 750, 650]
ads_spend = [50, 70, 60, 80, 90, 75, 65]
products_sold = [
    "sunflower", "broccoli", "sunflower",
    "basil", "sunflower", "broccoli", "sunflower"
]

# -------------------------------
# Import Libraries
# -------------------------------
import statistics

# -------------------------------
# Core Calculations
# -------------------------------

# Central tendency
# Calculate average sales
mean_sales = statistics.mean(sales)
median_sales = statistics.median(sales)
# Spread / variability
sales_range = max(sales) - min(sales)
variance_sales = statistics.pvariance(sales)
std_dev_sales = statistics.pstdev(sales)

# Most frequently sold product
most_sold_product = max(set(products_sold), key=products_sold.count)

# Relationship between ads and sales
correlation = statistics.correlation(ads_spend, sales)

# -------------------------------
# Output Section
# -------------------------------

print("\n--- Sales Analysis Summary ---\n")

print(f"Average Sales        : {mean_sales:.2f}")
print(f"Median Sales         : {median_sales}")
print(f"Sales Range          : {sales_range}")
print(f"Variance (Population): {variance_sales:.2f}")
print(f"Standard Deviation   : {std_dev_sales:.2f}")